### PR TITLE
Submits to Code Climate

### PR DESCRIPTION
**Pull request by zgosalvez**
**Known issue:**

```log
% CODECLIMATE_DEBUG=1 codeclimate analyze --dev
...truncated...
I, [2020-10-31T04:04:47.889734 #1]  INFO -- : starting engine dart
D, [2020-10-31T04:04:47.890442 #1] DEBUG -- : /config.json content: {"enabled"=>true, "channel"=>"stable", "include_paths"=>[".DS_Store", ".codeclimate.yml", ".dart_tool/", ".flutter-plugins", ".flutter-plugins-dependencies", ".github/", ".gitignore", ".idea/", ".metadata", ".packages", ".vscode/", ".whitesource", "analysis_options.yaml", "android/", "app.iml", "assets/", "build/", "coverage/", "ios/", "lib/", "pubspec.lock", "pubspec.yaml"], "debug"=>"1"}
D, [2020-10-31T04:04:47.892429 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-dart-stable-ff1a5ce6-06ac-480d-b0b9-53720f00b4db", "--cap-drop", "all", "--label", "com.codeclimate.label=28212475-1198-47c8-a6ca-1076205b89d1", "--log-driver", "none", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/Users/redacted/project:/code:ro", "--volume", "/tmp/cc/aa2567d6-43d4-4d17-9083-e14ae13fdde1:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-dart"]
D, [2020-10-31T04:04:50.214887 #1] DEBUG -- : engine stdout: [...redacted...]
#<Thread:0x000055d3b8d49860@/usr/src/app/lib/cc/analyzer/container.rb:120 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        8: from /usr/src/app/lib/cc/analyzer/container.rb:121:in `block in read_stdout'
        7: from /usr/src/app/lib/cc/analyzer/container.rb:121:in `each_line'
        6: from /usr/src/app/lib/cc/analyzer/container.rb:125:in `block (2 levels) in read_stdout'
        5: from /usr/src/app/lib/cc/analyzer/engine.rb:41:in `block in run'
        4: from /usr/src/app/lib/cc/analyzer/engine.rb:59:in `handle_output'
        3: from /usr/src/app/lib/cc/analyzer/engine_output_filter.rb:11:in `filter?'
        2: from /usr/src/app/lib/cc/analyzer/engine_output.rb:12:in `issue?'
        1: from /usr/src/app/lib/cc/analyzer/engine_output.rb:55:in `valid_with_type?'
/usr/src/app/lib/cc/analyzer/engine_output.rb:55:in `[]': no implicit conversion of String into Integer (TypeError)
error: (TypeError) no implicit conversion of String into Integer
D, [2020-10-31T04:04:50.280056 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/engine_output.rb:55:in `[]'
        /usr/src/app/lib/cc/analyzer/engine_output.rb:55:in `valid_with_type?'
        /usr/src/app/lib/cc/analyzer/engine_output.rb:12:in `issue?'
        /usr/src/app/lib/cc/analyzer/engine_output_filter.rb:11:in `filter?'
        /usr/src/app/lib/cc/analyzer/engine.rb:59:in `handle_output'
        /usr/src/app/lib/cc/analyzer/engine.rb:41:in `block in run'
        /usr/src/app/lib/cc/analyzer/container.rb:125:in `block (2 levels) in read_stdout'
        /usr/src/app/lib/cc/analyzer/container.rb:121:in `each_line'
        /usr/src/app/lib/cc/analyzer/container.rb:121:in `block in read_stdout'
```

### CODE REVIEW

**Comment by noelia-lencina** [comment]
Hi, @zgosalvez - I wanted to let you know I'll be looking into this. I hope to have more information soon. Thanks!

**Comment by zgosalvez** [comment]
Awesome, @noelia-lencina! Let me know if you need anything.

**Comment by noelia-lencina** [comment]
Hi, @zgosalvez ! I have some good news. I could figure out why the CLI was failing and the problem seems to be in the way the `metrics` command is printing to stdout. We have [this spec](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#output) where the format for the expected output is described. As noted there, each issue should be printed to stdout in json format **individually** and terminated with a null character. The current `metrics` command with the `--reporter=codeclimate` flag is printing it in json format but as an array (you can see that in the output of `CODECLIMATE_DEBUG=1 codeclimate analyze --dev`). 
Having said that, my suggestion would be to try to fix the issue in https://github.com/wrike/dart-code-metrics so it returns the issues in the correct format with the `--reporter=codeclimate` flag.
Let me know if this helps.

**Comment by zgosalvez** [comment]
@noelia-lencina, I'm afraid that didn't help since I am already aware that the reporter needs to be fixed but I don't know where to start. When I run `CODECLIMATE_DEBUG=1 codeclimate analyze --dev` it does show a JSON that is needed by the CLI. I was hoping you can help us identify where/what the issue exactly is.

**Comment by noelia-lencina** [comment]
@zgosalvez Sorry if I'm being repetitive here, just want to make sure I'm following. 
The problem is in the tool that's being used to generate the issue report ( https://github.com/wrike/dart-code-metrics ) and not in the Code Climate CLI neither in the new plugin. 
The problems is that https://github.com/wrike/dart-code-metrics is printing an **array** of issues in json format instead of **each issue in json format separated by a null character** as described in https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#output
So, in order to fix this, it will be necessary to fix the way https://github.com/wrike/dart-code-metrics is printing the issues to stdout.

Does this clarify where the problem is? I'm not sure about the exact place in the code of https://github.com/wrike/dart-code-metrics as I'm not familiar with that specific repo, but I guess there its maintainer could help.

Another option would be to modify the plugin so it takes the output from https://github.com/wrike/dart-code-metrics and does all the transformations to print the issues to stdout individually and terminated with a null character. I would say that it would be better to fix https://github.com/wrike/dart-code-metrics so it does what's intended, but if that's not an option, we could take this other path.

I saw that you opened an issue in the repo asking for more information. I subscribed to it so I can get notified once the maintainer responds, in case I can be of any help there.

**Comment by zgosalvez** [comment]
Closing this PR in lieu of wrike/codeclimate-dart#2. Thank you for the assist @noelia-lencina! 🙏

**Pull request closed without merging**
